---
title: "plotly"
author: "samado"
date: "December 22, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r, echo=FALSE ,warning=FALSE ,include=FALSE}
library(plotly)
```

```{r, echo=FALSE ,warning=FALSE}
f <- list(
  family = "Courier New, monospace",
  size = 11,   color = "#6e6e6e" )
x <- list(
  title = "Weight (1000 lbs)",   titlefont = f )

y <- list(
  title = "Mileage per gallon",   titlefont = f )
```

```{r , eval=FALSE ,warning=FALSE ,echo=FALSE}
plot_ly(mtcars, x = mtcars$wt, y=mtcars$mpg, mode="markers", 
        type="scatter",color=as.factor(mtcars$cyl), size=mtcars$hp ) %>%   
        layout(xaxis=x, yaxis=y)
```
## Slide with Plot

```{r , echo=FALSE ,warning=FALSE}
plot_ly(mtcars, x = mtcars$wt, y=mtcars$mpg, mode="markers",showlegend=TRUE, 
        type="scatter",color=as.factor(mtcars$cyl), size=mtcars$hp ) %>%   
        layout(xaxis=x, yaxis=y)
```

##thanks

